
\restrict Fdbi41gnCFS6ZdLEiSH4Ss5g1PiwbtDJtxSQk8WXPqkapHD6mv29TJWZXonsweE


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."informeAreaDesarrollo" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "nombre" "text",
    "comment" "text",
    "informeId" bigint,
    "evaluadoId" bigint
);


ALTER TABLE "public"."informeAreaDesarrollo" OWNER TO "postgres";


ALTER TABLE "public"."informeAreaDesarrollo" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."areaDesarrollo_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."aspiraciones" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "nombre" "text",
    "lang" "text"
);


ALTER TABLE "public"."aspiraciones" OWNER TO "postgres";


ALTER TABLE "public"."aspiraciones" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."aspiraciones_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."auth_tokens" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "email" "text",
    "access_token" "text",
    "refresh_token" "text",
    "token_expiry" timestamp without time zone
);


ALTER TABLE "public"."auth_tokens" OWNER TO "postgres";


ALTER TABLE "public"."auth_tokens" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."auth_tokens_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."colores" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "nombre" "text",
    "codigo" "text"
);


ALTER TABLE "public"."colores" OWNER TO "postgres";


ALTER TABLE "public"."colores" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."colores_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."company" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "nombre" "text",
    "telefono" "text",
    "emailContacto" "text",
    "estado" "text",
    "project_start_date" "date"
);


ALTER TABLE "public"."company" OWNER TO "postgres";


ALTER TABLE "public"."company" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."company_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."competenciaCompany" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "competenciaId" bigint,
    "companyId" bigint
);


ALTER TABLE "public"."competenciaCompany" OWNER TO "postgres";


ALTER TABLE "public"."competenciaCompany" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."competenciaCompany_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."competencias" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "nombre" "text"
);


ALTER TABLE "public"."competencias" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."competenciasComparativa" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "evaluadoId" bigint,
    "competencia" bigint,
    "nivelId" bigint,
    "anio" "text",
    "tipo" "text"
);


ALTER TABLE "public"."competenciasComparativa" OWNER TO "postgres";


ALTER TABLE "public"."competenciasComparativa" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."competenciasComparativa_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."nivelesCompetencias" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "nombre" "text",
    "lang" "text",
    "order" integer,
    "colorId" bigint,
    "ponderacion" smallint
);


ALTER TABLE "public"."nivelesCompetencias" OWNER TO "postgres";


ALTER TABLE "public"."nivelesCompetencias" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."competencias_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."competencias" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."competencias_id_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."project_phases" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "etapa" "text",
    "days_duration" double precision,
    "days_from_last" double precision,
    "order" bigint,
    "type" "text",
    "colour" "text"
);


ALTER TABLE "public"."project_phases" OWNER TO "postgres";


ALTER TABLE "public"."project_phases" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."etapas_proyecto_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."evaluado" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "companyId" bigint,
    "consultora" bigint,
    "idioma" bigint,
    "region" "text",
    "id_empleado" "text",
    "nombre" "text",
    "correo_electronico" "text",
    "telefono" "text",
    "hotel" "text",
    "departamento" "text",
    "posicion" "text",
    "fecha_nacimiento" "date",
    "fecha_entrada" "date",
    "evaluacion_2024" "text",
    "evaluadora" "text",
    "cita_ok" boolean,
    "entrevista_ok" boolean,
    "cancelacion_1" boolean,
    "cancelacion_2" boolean,
    "cv" boolean,
    "bfq" boolean,
    "pais" "text",
    "genero" "text"
);


ALTER TABLE "public"."evaluado" OWNER TO "postgres";


ALTER TABLE "public"."evaluado" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."evaluado_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."idiomaNivel" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "nombre" "text",
    "lang" "text"
);


ALTER TABLE "public"."idiomaNivel" OWNER TO "postgres";


ALTER TABLE "public"."idiomaNivel" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."idiomaNivel_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."informeIdiomaNiveles" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "idiomaId" bigint,
    "evaluadoId" bigint,
    "nivelId" bigint,
    "informeId" bigint
);


ALTER TABLE "public"."informeIdiomaNiveles" OWNER TO "postgres";


ALTER TABLE "public"."informeIdiomaNiveles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."idiomaNiveles_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."idiomas" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "idioma" "text",
    "lang" "text"
);


ALTER TABLE "public"."idiomas" OWNER TO "postgres";


ALTER TABLE "public"."idiomas" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."idiomas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."informe" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "evaluadoId" bigint,
    "consultoraId" bigint,
    "formacionAcademica" "text",
    "experienciaProfesional" "text",
    "updated_date" "text",
    "capacidadPotencialActual" "text",
    "capacidadPotencialFutura" "text",
    "recomendaciones" "text",
    "propuestasDesarrollo" "text",
    "conclusiones" "text",
    "potencial" "text",
    "cpa5" "text",
    "cpa10" "text",
    "modo" "text",
    "disponibilidad" "text",
    "breveDescripcionDisponibilidad" "text",
    "disponibilidadComment" "text",
    "tipoInformeId" bigint,
    "balanceNivel" "text",
    "balanceDescripcion" "text"
);


ALTER TABLE "public"."informe" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."informeAspiraciones" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "aspiracionesId" bigint,
    "comment" "text",
    "informeId" bigint,
    "evaluadoId" bigint,
    "breveDescripcion" "text"
);


ALTER TABLE "public"."informeAspiraciones" OWNER TO "postgres";


ALTER TABLE "public"."informeAspiraciones" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."informeAspiraciones_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."informeFortalezas" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "nombre" "text",
    "comment" "text",
    "informeId" bigint,
    "evaluadoId" bigint
);


ALTER TABLE "public"."informeFortalezas" OWNER TO "postgres";


ALTER TABLE "public"."informeFortalezas" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."informeFortalezas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."informeTipo" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "tipoInforme" "text"
);


ALTER TABLE "public"."informeTipo" OWNER TO "postgres";


ALTER TABLE "public"."informeTipo" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."informeTipo_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."informeValoracionCompetencia" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "texto" "text",
    "evaluadoId" bigint,
    "competenciaNombre" "text",
    "nivelId" bigint,
    "informeId" bigint,
    "anio" integer DEFAULT (EXTRACT(year FROM "now"()))::integer
);


ALTER TABLE "public"."informeValoracionCompetencia" OWNER TO "postgres";


ALTER TABLE "public"."informeValoracionCompetencia" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."informeValoracionCompetencia_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."informe" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."informe_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE OR REPLACE VIEW "public"."informeareadesarrollo" AS
 SELECT "informeAreaDesarrollo"."id",
    "informeAreaDesarrollo"."created_at",
    "informeAreaDesarrollo"."nombre",
    "informeAreaDesarrollo"."comment",
    "informeAreaDesarrollo"."informeId",
    "informeAreaDesarrollo"."evaluadoId"
   FROM "public"."informeAreaDesarrollo";


ALTER VIEW "public"."informeareadesarrollo" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."informeaspiraciones" AS
 SELECT "informeAspiraciones"."id",
    "informeAspiraciones"."created_at",
    "informeAspiraciones"."aspiracionesId",
    "informeAspiraciones"."comment",
    "informeAspiraciones"."informeId",
    "informeAspiraciones"."evaluadoId",
    "informeAspiraciones"."breveDescripcion"
   FROM "public"."informeAspiraciones";


ALTER VIEW "public"."informeaspiraciones" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."informefortalezas" AS
 SELECT "informeFortalezas"."id",
    "informeFortalezas"."created_at",
    "informeFortalezas"."nombre",
    "informeFortalezas"."comment",
    "informeFortalezas"."informeId",
    "informeFortalezas"."evaluadoId"
   FROM "public"."informeFortalezas";


ALTER VIEW "public"."informefortalezas" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."informeidiomaniveles" AS
 SELECT "informeIdiomaNiveles"."id",
    "informeIdiomaNiveles"."created_at",
    "informeIdiomaNiveles"."idiomaId",
    "informeIdiomaNiveles"."evaluadoId",
    "informeIdiomaNiveles"."nivelId",
    "informeIdiomaNiveles"."informeId"
   FROM "public"."informeIdiomaNiveles";


ALTER VIEW "public"."informeidiomaniveles" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."informetipo" AS
 SELECT "informeTipo"."id",
    "informeTipo"."created_at",
    "informeTipo"."tipoInforme"
   FROM "public"."informeTipo";


ALTER VIEW "public"."informetipo" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."informevaloracioncompetencia" AS
 SELECT "informeValoracionCompetencia"."id",
    "informeValoracionCompetencia"."created_at",
    "informeValoracionCompetencia"."texto",
    "informeValoracionCompetencia"."evaluadoId",
    "informeValoracionCompetencia"."competenciaNombre",
    "informeValoracionCompetencia"."nivelId",
    "informeValoracionCompetencia"."informeId",
    "informeValoracionCompetencia"."anio"
   FROM "public"."informeValoracionCompetencia";


ALTER VIEW "public"."informevaloracioncompetencia" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."nivelescompentencia" AS
 SELECT "nivelesCompetencias"."id",
    "nivelesCompetencias"."created_at",
    "nivelesCompetencias"."nombre",
    "nivelesCompetencias"."lang",
    "nivelesCompetencias"."order",
    "nivelesCompetencias"."colorId",
    "nivelesCompetencias"."ponderacion"
   FROM "public"."nivelesCompetencias";


ALTER VIEW "public"."nivelescompentencia" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."roles" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "rol" "text",
    "description" "text"
);


ALTER TABLE "public"."roles" OWNER TO "postgres";


ALTER TABLE "public"."roles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."roles_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."users1" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "email" character varying,
    "password" "text",
    "language" "text",
    "nombre" "text",
    "estado" "text",
    "companyId" bigint,
    "rol" bigint
);


ALTER TABLE "public"."users1" OWNER TO "postgres";


COMMENT ON TABLE "public"."users1" IS 'users and roles';



ALTER TABLE "public"."users1" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE OR REPLACE VIEW "public"."vista_evaluacion" AS
 SELECT "e"."id",
    "e"."evaluacion_2024",
    "i"."potencial",
        CASE
            WHEN (("e"."evaluacion_2024" = 'Excelente_120%'::"text") AND ("i"."potencial" = 'Alto'::"text")) THEN 'Cuadrante 9: Potencial Alto / Rendimiento Excelente'::"text"
            WHEN (("e"."evaluacion_2024" = 'Supera_110%'::"text") AND ("i"."potencial" = 'Alto'::"text")) THEN 'Cuadrante 8: Potencial Alto / Rendimiento Superior'::"text"
            WHEN (("e"."evaluacion_2024" = ANY (ARRAY['Cumple_100%'::"text", '100%'::"text"])) AND ("i"."potencial" = 'Alto'::"text")) THEN 'Cuadrante 7: Potencial Alto / Rendimiento Cumple'::"text"
            WHEN (("e"."evaluacion_2024" = 'Cumple Parcialmente_75%'::"text") AND ("i"."potencial" = 'Alto'::"text")) THEN 'Cuadrante P: Potencial Alto / Rendimiento Parcial'::"text"
            WHEN (("e"."evaluacion_2024" = 'Cumple Mínimo_50%'::"text") AND ("i"."potencial" = 'Alto'::"text")) THEN 'Cuadrante Q: Potencial Alto / Rendimiento Mínimo'::"text"
            WHEN (("e"."evaluacion_2024" = 'Excelente_120%'::"text") AND ("i"."potencial" = 'Medio'::"text")) THEN 'Cuadrante 6: Potencial Medio / Rendimiento Excelente'::"text"
            WHEN (("e"."evaluacion_2024" = 'Supera_110%'::"text") AND ("i"."potencial" = 'Medio'::"text")) THEN 'Cuadrante 5: Potencial Medio / Rendimiento Superior'::"text"
            WHEN (("e"."evaluacion_2024" = ANY (ARRAY['Cumple_100%'::"text", '100%'::"text"])) AND ("i"."potencial" = 'Medio'::"text")) THEN 'Cuadrante 4: Potencial Medio / Rendimiento Cumple'::"text"
            WHEN (("e"."evaluacion_2024" = 'Cumple Parcialmente_75%'::"text") AND ("i"."potencial" = 'Medio'::"text")) THEN 'Cuadrante Z: Potencial Medio / Rendimiento Parcial'::"text"
            WHEN (("e"."evaluacion_2024" = 'Cumple Mínimo_50%'::"text") AND ("i"."potencial" = 'Medio'::"text")) THEN 'Cuadrante W: Potencial Medio / Rendimiento Mínimo'::"text"
            WHEN (("e"."evaluacion_2024" = 'Excelente_120%'::"text") AND ("i"."potencial" = 'Bajo'::"text")) THEN 'Cuadrante 3: Potencial Bajo / Rendimiento Excelente'::"text"
            WHEN (("e"."evaluacion_2024" = 'Supera_110%'::"text") AND ("i"."potencial" = 'Bajo'::"text")) THEN 'Cuadrante 2: Potencial Bajo / Rendimiento Superior'::"text"
            WHEN (("e"."evaluacion_2024" = ANY (ARRAY['Cumple_100%'::"text", '100%'::"text"])) AND ("i"."potencial" = 'Bajo'::"text")) THEN 'Cuadrante 1: Potencial Bajo / Rendimiento Cumple'::"text"
            WHEN (("e"."evaluacion_2024" = 'Cumple Parcialmente_75%'::"text") AND ("i"."potencial" = 'Bajo'::"text")) THEN 'Cuadrante X: Potencial Bajo / Rendimiento Parcial'::"text"
            WHEN (("e"."evaluacion_2024" = 'Cumple Mínimo_50%'::"text") AND ("i"."potencial" = 'Bajo'::"text")) THEN 'Cuadrante Y: Potencial Bajo / Rendimiento Mínimo'::"text"
            ELSE 'No Definido'::"text"
        END AS "box"
   FROM ("public"."evaluado" "e"
     JOIN "public"."informe" "i" ON (("e"."id" = "i"."evaluadoId")));


ALTER VIEW "public"."vista_evaluacion" OWNER TO "postgres";


ALTER TABLE ONLY "public"."informeAreaDesarrollo"
    ADD CONSTRAINT "areaDesarrollo_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."aspiraciones"
    ADD CONSTRAINT "aspiraciones_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."auth_tokens"
    ADD CONSTRAINT "auth_tokens_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."colores"
    ADD CONSTRAINT "colores_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."company"
    ADD CONSTRAINT "company_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."competenciaCompany"
    ADD CONSTRAINT "competenciaCompany_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."competenciasComparativa"
    ADD CONSTRAINT "competenciasComparativa_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."nivelesCompetencias"
    ADD CONSTRAINT "competencias_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."competencias"
    ADD CONSTRAINT "competencias_pkey1" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."project_phases"
    ADD CONSTRAINT "etapas_proyecto_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."evaluado"
    ADD CONSTRAINT "evaluado_correo_electronico_key" UNIQUE ("correo_electronico");



ALTER TABLE ONLY "public"."evaluado"
    ADD CONSTRAINT "evaluado_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."idiomaNivel"
    ADD CONSTRAINT "idiomaNivel_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."informeIdiomaNiveles"
    ADD CONSTRAINT "idiomaNiveles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."idiomas"
    ADD CONSTRAINT "idiomas_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."informeAspiraciones"
    ADD CONSTRAINT "informeAspiraciones_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."informeFortalezas"
    ADD CONSTRAINT "informeFortalezas_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."informeTipo"
    ADD CONSTRAINT "informeTipo_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."informeValoracionCompetencia"
    ADD CONSTRAINT "informeValoracionCompetencia_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."informe"
    ADD CONSTRAINT "informe_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."roles"
    ADD CONSTRAINT "roles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."competencias"
    ADD CONSTRAINT "unique_nombre" UNIQUE ("nombre");



ALTER TABLE ONLY "public"."users1"
    ADD CONSTRAINT "users_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."users1"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."informeAreaDesarrollo"
    ADD CONSTRAINT "areaDesarrollo_evaluadoId_fkey" FOREIGN KEY ("evaluadoId") REFERENCES "public"."evaluado"("id");



ALTER TABLE ONLY "public"."informeAreaDesarrollo"
    ADD CONSTRAINT "areaDesarrollo_informeId_fkey" FOREIGN KEY ("informeId") REFERENCES "public"."informe"("id");



ALTER TABLE ONLY "public"."competenciaCompany"
    ADD CONSTRAINT "competenciaCompany_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "public"."company"("id");



ALTER TABLE ONLY "public"."competenciaCompany"
    ADD CONSTRAINT "competenciaCompany_competenciaId_fkey" FOREIGN KEY ("competenciaId") REFERENCES "public"."competencias"("id");



ALTER TABLE ONLY "public"."competenciasComparativa"
    ADD CONSTRAINT "competenciasComparativa_competencia_fkey" FOREIGN KEY ("competencia") REFERENCES "public"."competencias"("id");



ALTER TABLE ONLY "public"."competenciasComparativa"
    ADD CONSTRAINT "competenciasComparativa_evaluadoId_fkey" FOREIGN KEY ("evaluadoId") REFERENCES "public"."evaluado"("id");



ALTER TABLE ONLY "public"."competenciasComparativa"
    ADD CONSTRAINT "competenciasComparativa_nivelId_fkey" FOREIGN KEY ("nivelId") REFERENCES "public"."nivelesCompetencias"("id");



ALTER TABLE ONLY "public"."evaluado"
    ADD CONSTRAINT "evaluado_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "public"."company"("id");



ALTER TABLE ONLY "public"."evaluado"
    ADD CONSTRAINT "evaluado_consultora_fkey" FOREIGN KEY ("consultora") REFERENCES "public"."users1"("id");



ALTER TABLE ONLY "public"."evaluado"
    ADD CONSTRAINT "evaluado_idioma_fkey" FOREIGN KEY ("idioma") REFERENCES "public"."idiomas"("id");



ALTER TABLE ONLY "public"."informeIdiomaNiveles"
    ADD CONSTRAINT "idiomaNiveles_evaluadoId_fkey" FOREIGN KEY ("evaluadoId") REFERENCES "public"."evaluado"("id");



ALTER TABLE ONLY "public"."informeIdiomaNiveles"
    ADD CONSTRAINT "idiomaNiveles_idiomaId_fkey" FOREIGN KEY ("idiomaId") REFERENCES "public"."idiomas"("id");



ALTER TABLE ONLY "public"."informeAspiraciones"
    ADD CONSTRAINT "informeAspiraciones_aspiracionesId_fkey" FOREIGN KEY ("aspiracionesId") REFERENCES "public"."aspiraciones"("id");



ALTER TABLE ONLY "public"."informeAspiraciones"
    ADD CONSTRAINT "informeAspiraciones_evaluadoId_fkey" FOREIGN KEY ("evaluadoId") REFERENCES "public"."evaluado"("id");



ALTER TABLE ONLY "public"."informeAspiraciones"
    ADD CONSTRAINT "informeAspiraciones_informeId_fkey" FOREIGN KEY ("informeId") REFERENCES "public"."informe"("id");



ALTER TABLE ONLY "public"."informeFortalezas"
    ADD CONSTRAINT "informeFortalezas_evaluadoId_fkey" FOREIGN KEY ("evaluadoId") REFERENCES "public"."evaluado"("id");



ALTER TABLE ONLY "public"."informeFortalezas"
    ADD CONSTRAINT "informeFortalezas_informeId_fkey" FOREIGN KEY ("informeId") REFERENCES "public"."informe"("id");



ALTER TABLE ONLY "public"."informeIdiomaNiveles"
    ADD CONSTRAINT "informeIdiomaNiveles_informeId_fkey" FOREIGN KEY ("informeId") REFERENCES "public"."informe"("id");



ALTER TABLE ONLY "public"."informeIdiomaNiveles"
    ADD CONSTRAINT "informeIdiomaNiveles_nivelId_fkey" FOREIGN KEY ("nivelId") REFERENCES "public"."idiomaNivel"("id");



ALTER TABLE ONLY "public"."informeValoracionCompetencia"
    ADD CONSTRAINT "informeValoracionCompetencia_evaluadoId_fkey" FOREIGN KEY ("evaluadoId") REFERENCES "public"."evaluado"("id");



ALTER TABLE ONLY "public"."informeValoracionCompetencia"
    ADD CONSTRAINT "informeValoracionCompetencia_informeId_fkey" FOREIGN KEY ("informeId") REFERENCES "public"."informe"("id");



ALTER TABLE ONLY "public"."informeValoracionCompetencia"
    ADD CONSTRAINT "informeValoracionCompetencia_nivelId_fkey" FOREIGN KEY ("nivelId") REFERENCES "public"."nivelesCompetencias"("id");



ALTER TABLE ONLY "public"."informe"
    ADD CONSTRAINT "informe_consultoraId_fkey" FOREIGN KEY ("consultoraId") REFERENCES "public"."users1"("id");



ALTER TABLE ONLY "public"."informe"
    ADD CONSTRAINT "informe_evaluadoId_fkey" FOREIGN KEY ("evaluadoId") REFERENCES "public"."evaluado"("id");



ALTER TABLE ONLY "public"."informe"
    ADD CONSTRAINT "informe_tipoInformeId_fkey" FOREIGN KEY ("tipoInformeId") REFERENCES "public"."informeTipo"("id");



ALTER TABLE ONLY "public"."nivelesCompetencias"
    ADD CONSTRAINT "nivelesCompetencias_colorId_fkey" FOREIGN KEY ("colorId") REFERENCES "public"."colores"("id");



ALTER TABLE ONLY "public"."users1"
    ADD CONSTRAINT "users_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "public"."company"("id");



ALTER TABLE ONLY "public"."users1"
    ADD CONSTRAINT "users_rol_fkey" FOREIGN KEY ("rol") REFERENCES "public"."roles"("id");



ALTER TABLE "public"."aspiraciones" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."auth_tokens" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."colores" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."company" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."competenciaCompany" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."competencias" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."competenciasComparativa" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "ead" ON "public"."competenciasComparativa" USING (true) WITH CHECK (true);



ALTER TABLE "public"."evaluado" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."idiomaNivel" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."idiomas" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."informe" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."informeAreaDesarrollo" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."informeAspiraciones" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."informeFortalezas" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."informeIdiomaNiveles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."informeTipo" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."informeValoracionCompetencia" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."nivelesCompetencias" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."project_phases" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "read" ON "public"."aspiraciones" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."colores" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."competenciaCompany" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."competencias" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."evaluado" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."idiomaNivel" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."idiomas" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."informe" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."informeAreaDesarrollo" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."informeAspiraciones" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."informeFortalezas" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."informeIdiomaNiveles" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."informeTipo" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."informeValoracionCompetencia" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."nivelesCompetencias" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."project_phases" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."roles" USING (true) WITH CHECK (true);



CREATE POLICY "read_write" ON "public"."auth_tokens" USING (true) WITH CHECK (true);



CREATE POLICY "read_write" ON "public"."company" USING (true) WITH CHECK (true);



CREATE POLICY "read_write" ON "public"."users1" USING (true) WITH CHECK (true);



ALTER TABLE "public"."roles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."users1" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";


























































































































































































GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informeAreaDesarrollo" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informeAreaDesarrollo" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informeAreaDesarrollo" TO "service_role";



GRANT ALL ON SEQUENCE "public"."areaDesarrollo_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."areaDesarrollo_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."areaDesarrollo_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."aspiraciones" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."aspiraciones" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."aspiraciones" TO "service_role";



GRANT ALL ON SEQUENCE "public"."aspiraciones_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."aspiraciones_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."aspiraciones_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."auth_tokens" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."auth_tokens" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."auth_tokens" TO "service_role";



GRANT ALL ON SEQUENCE "public"."auth_tokens_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."auth_tokens_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."auth_tokens_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."colores" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."colores" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."colores" TO "service_role";



GRANT ALL ON SEQUENCE "public"."colores_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."colores_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."colores_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."company" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."company" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."company" TO "service_role";



GRANT ALL ON SEQUENCE "public"."company_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."company_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."company_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."competenciaCompany" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."competenciaCompany" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."competenciaCompany" TO "service_role";



GRANT ALL ON SEQUENCE "public"."competenciaCompany_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."competenciaCompany_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."competenciaCompany_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."competencias" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."competencias" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."competencias" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."competenciasComparativa" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."competenciasComparativa" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."competenciasComparativa" TO "service_role";



GRANT ALL ON SEQUENCE "public"."competenciasComparativa_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."competenciasComparativa_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."competenciasComparativa_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."nivelesCompetencias" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."nivelesCompetencias" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."nivelesCompetencias" TO "service_role";



GRANT ALL ON SEQUENCE "public"."competencias_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."competencias_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."competencias_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."competencias_id_seq1" TO "anon";
GRANT ALL ON SEQUENCE "public"."competencias_id_seq1" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."competencias_id_seq1" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."project_phases" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."project_phases" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."project_phases" TO "service_role";



GRANT ALL ON SEQUENCE "public"."etapas_proyecto_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."etapas_proyecto_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."etapas_proyecto_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."evaluado" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."evaluado" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."evaluado" TO "service_role";



GRANT ALL ON SEQUENCE "public"."evaluado_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."evaluado_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."evaluado_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."idiomaNivel" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."idiomaNivel" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."idiomaNivel" TO "service_role";



GRANT ALL ON SEQUENCE "public"."idiomaNivel_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."idiomaNivel_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."idiomaNivel_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informeIdiomaNiveles" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informeIdiomaNiveles" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informeIdiomaNiveles" TO "service_role";



GRANT ALL ON SEQUENCE "public"."idiomaNiveles_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."idiomaNiveles_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."idiomaNiveles_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."idiomas" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."idiomas" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."idiomas" TO "service_role";



GRANT ALL ON SEQUENCE "public"."idiomas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."idiomas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."idiomas_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informe" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informe" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informe" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informeAspiraciones" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informeAspiraciones" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informeAspiraciones" TO "service_role";



GRANT ALL ON SEQUENCE "public"."informeAspiraciones_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."informeAspiraciones_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."informeAspiraciones_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informeFortalezas" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informeFortalezas" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informeFortalezas" TO "service_role";



GRANT ALL ON SEQUENCE "public"."informeFortalezas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."informeFortalezas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."informeFortalezas_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informeTipo" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informeTipo" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informeTipo" TO "service_role";



GRANT ALL ON SEQUENCE "public"."informeTipo_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."informeTipo_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."informeTipo_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informeValoracionCompetencia" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informeValoracionCompetencia" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informeValoracionCompetencia" TO "service_role";



GRANT ALL ON SEQUENCE "public"."informeValoracionCompetencia_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."informeValoracionCompetencia_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."informeValoracionCompetencia_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."informe_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."informe_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."informe_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informeareadesarrollo" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informeareadesarrollo" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informeareadesarrollo" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informeaspiraciones" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informeaspiraciones" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informeaspiraciones" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informefortalezas" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informefortalezas" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informefortalezas" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informeidiomaniveles" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informeidiomaniveles" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informeidiomaniveles" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informetipo" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informetipo" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informetipo" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informevaloracioncompetencia" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informevaloracioncompetencia" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."informevaloracioncompetencia" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."nivelescompentencia" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."nivelescompentencia" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."nivelescompentencia" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."roles" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."roles" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."roles" TO "service_role";



GRANT ALL ON SEQUENCE "public"."roles_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."roles_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."roles_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."users1" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."users1" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."users1" TO "service_role";



GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."vista_evaluacion" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."vista_evaluacion" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."vista_evaluacion" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO "service_role";






























\unrestrict Fdbi41gnCFS6ZdLEiSH4Ss5g1PiwbtDJtxSQk8WXPqkapHD6mv29TJWZXonsweE

RESET ALL;
