phasesTable = "project_phases"
companyTable ="company"
usersTable="users"
authTokenTable="auth_tokens"
evaluadoTable="evaluado"
informeTable="informe"
idiomasTable="idiomas"
aspiracionesTable="aspiraciones"
informeAspiraciones="informeAspiraciones"
idiomasNivelesTable="idiomaNivel"
informeIdiomaNivelesTable="informeIdiomaNiveles"
informeValoracionCompetencia="informeValoracionCompetencia"
informeFortalezasTable="informeFortalezas"
informeAreaDesarrollo="informeAreaDesarrollo"
nivelesCompetenciasTable="nivelesCompetencias"


