texts = {
  "greetings": "Hello",
  "title": "Welcome to P+Data",
  "username": "Email",
  "password": "Password",
  "forgotPassword": "Forgot my password",
  "loginButton": "Log In",
  "logoutButton": "Log Out",
  "errorRedirection": "Session expired. Redirecting to login...",
  "IncorrectPassword": "Incorrect email or password. Please try again",
  "homeLoginRedirect": "Redirecting to login page...",
  "logoutMessage": "Logged out successfully",
  "loginMessage": "Successfully logged in",
  "loginDescription": "Please log in to get started",
  "titleRegisterUser": "📋 Registered Users",
  "titleUsers": "Users",
  "titleClients": "Clients",
  "titleCalendar": "Schedule",
  "titleInterview": "Interview",
  "titlePreliminarData": "Preliminary Data",
  "connectToGoogle": "Connect with Google Calendar",
  "calendarNoEvents": "No upcoming events.",
  "calendarLinkButton": "Add or edit meeting",
  "homePageTitle": "Attract, Hire and Develop Talent",
  "homePageSubtitle": "Our platform powered by AI and grounded in advanced behavioral science enables success and performance in candidates for any role.",
  "homeBenefits": "Benefits",
  "homeClientsTitle": "What do our clients say?",
  "homeTestimonial": [
    {"name": "Ana García", "testimonial": "This platform changed the way we hire. The results have been amazing."},
    {"name": "Carlos Méndez", "testimonial": "The system helped us identify high-potential candidates we wouldn’t have considered otherwise."},
    {"name": "Laura Pérez", "testimonial": "Thanks to the platform, we now have more engaged and productive employees."}
  ],
  "menuClientPlanning": "Planning",
  "InterviewDropdownText": "Person to evaluate",
  "InverviewTitlePerfilProfesional": "PROFESSIONAL PROFILE",
  "InterviewValoracionCompentencias": "COMPETENCY EVALUATION",
  "InterviewEvaluacionPotencial": "POTENTIAL EVALUATION",
  "InterviewBalanceEmocional": "EMOTIONAL BALANCE",
  "InterviewMotivacionIntereses": "MOTIVATIONS AND INTERESTS",
  "InterviewMotivacionesSubtitle": "Growth Aspiration",
  "InterviewDisponibildadGeografica": "Geographic Availability",
  "InterviewDisponibilidadList": ["Partial", "Full", "None"],
  "InterviewBreveDescripcion": "Brief Description",
  "InterviewConclusiones": "CONCLUSIONS",
  "InterviewFormacionAcademicaText": "Academic Background",
  "InterviewLanguages": "Languages",
  "InterviewIdiomas": ["Spanish", "English", "Portuguese"],
  "InterviewSelectLang": "Select a language:",
  "InterviewSelectLangNivel": "Select your level:",
  "InterviewSelectAddLang": "Add Language",
  "InterviewSelectAddedLang": "Added languages:",
  "InterviewLangAlreadyAdded": "This language has already been added.",
  "InterviewExperienciaProfesional": "Professional Experience",
  "InterviewSaveButton": "Save report",
  "InterviewCreateFile": "Generate report",
  "InverviewCompetenceTitle": "Competency Evaluation",
  "InverviewCompetenceAdd": "Enter a competency",
  "AddButton": "Add",
  "DeleteButton": "Delete",
  "NoDataYet": "No data yet",
  "InverviewCompetenceAdded": "Added competencies:",
  "InverviewMotivacionAdded": "Added aspirations:",
  "InterviewFortalezayAreasDesarrollo": "Strengths and Development Areas",
  "InverviewFortalezaAdded": "Added strengths:",
  "InterviewFortalezaTitle": "Strengths",
  "InterviewAreaTitle": "Development Areas",
  "InverviewAreasAdded": "Added areas:",
  "InverviewPotencial": "Potential:",
  "InterviewPotencialNivel": ["High", "Medium", "Low"],
  "InterviewCapacidadPotencialActual": "Current Potential Capacity",
  "InterviewCapacidadPotencialFutura": "Future Potential Capacity",
  "InterviewGraficoProgreso": "Potential Progress Chart",
  "InterviewCPA": ["IB", "IM", "IA", "IIB", "IIM", "IIA", "IIIB", "IIIM", "IIIA", "IVB", "IVM", "IVA", "VB", "VM", "VA"],
  "InterviewCPA5Title": "CPA IN 5 YEARS",
  "InterviewCPA10Title": "CPA IN 10 YEARS",
  "InterviewModo": ["I", "II", "III", "IV", "V", "VI", "VII"],
  "InterviewModoTitle": "MODE",
  "InterviewConclusionesTitle": "CONCLUSIONS",
  "InterviewConclusiones": "Conclusions",
  "InterviewRecomendaciones": "Recommendations",
  "InterviewAccionesDesarrollo": "Development action proposal",
  "Valor": "Value",
  "Comment": "Comment:",
  "SelectValue": "Select a value",
  "dataSavedCorrectlyMessage": "Data saved successfully",
  "dataSavedErrorMessage": "Error saving data",
  "dataNoReportFound": "No report found, please save before generating the report"
}
