texts = {
    "greetings": "Hello",
    "title": "Welcome to P+Data",
    "username": "Email",
    "password": "Password",
    "forgotPassword": "Forgot my password",
    "loginButton": "Log In",
    "logoutButton": "Log Out",
    "errorRedirection": "Session expired. Redirecting to login...",
    "IncorrectPassword": "Incorrect email or password. Please try again",
    "homeLoginRedirect": "Redirecting to login page...",
    "logoutMessage": "Successfully logged out",
    "loginMessage": "Successfully logged in",
    "loginDescription": "Please log in to get started",
    "titleRegisterUser": "📋 Registered Users",
    "titleUsers": "Users",
    "titleClients": "Clients",
    "titleCalendar": "Calendar",
    "titleInterview": "Interview",
    "titlePreliminarData": "Preliminary Data",
    "connectToGoogle": "Connect with Google Calendar",
    "calendarNoEvents": "No upcoming events.",
    "calendarLinkButton": "Add or modify meeting",
    "homePageTitle": "Attract, Hire and Develop Talent",
    "homePageSubtitle": "Our AI-powered platform, configured with advanced behavioral science, enables the success and performance of candidates for any position.",
    "homeBenefits": "Benefits",
    "homeClientsTitle": "What do our clients say?",
    "homeTestimonial": [
        {"name": "Ana García", "testimonial": "This platform changed the way we hire. The results have been amazing."},
        {"name": "Carlos Méndez", "testimonial": "The system helped us identify high-potential candidates we wouldn't have otherwise considered."},
        {"name": "Laura Pérez", "testimonial": "Thanks to the platform, we now have more engaged and productive employees."}
    ],
    "menuClientPlanning": "Planning",
    "InterviewDropdownText": "Person to evaluate",
    "InterviewFormacionAcademicaText": "Academic Background",
    "InterviewLanguages": "Languages",
    "InterviewIdiomas": ["Spanish", "English", "Portuguese"],
    "InterviewSelectLang": "Select a language:",
    "InterviewSelectLangNivel": "Select your level:",
    "InterviewSelectAddLang": "Add Language",
    "InterviewSelectAddedLang": "Added languages:",
    "InterviewLangAlreadyAdded": "This language has already been added.",
    "InterviewExperienciaProfesional": "Professional Experience",
    "InterviewSaveButton": "Save report",
    "InterviewCreateFile": "Generate report",
    "InverviewCompetenceTitle": "Competency Assessment",
    "InverviewCompetenceAdd": "Enter a competency",
    "InterviewCapacidadPotencialActual": "Current Potential Capacity",
    "InterviewCapacidadPotencialFutura": "Future Potential Capacity",
    "InterviewConclusiones": "Conclusions",
    "InterviewRecomendaciones": "Recommendations",
    "InterviewAccionesDesarrollo": "Suggested development actions",
    "Valor": "Value",
    "Comment": "Comment",
    "SelectValue": "Select a value",
    "dataSavedCorrectlyMessage": "Data saved successfully",
    "dataSavedErrorMessage": "Error while saving",
    "dataNoReportFound": "No report found, please save before generating the report"
}
