texts = {
    "greetings": "Hello",
    "title": "Welcome to P+Data",
    "username": "Email",
    "password": "Password",
    "forgotPassword": "Forgot my password",
    "loginButton": "Log In",
    "logoutButton": "Log Out",
    "errorRedirection": "Session expired. Redirecting to login...",
    "IncorrectPassword": "Incorrect email or password. Please try again.",
    "homeLoginRedirect": "Redirecting to the login page...",
    "logoutMessage": "Successfully logged out",
    "loginMessage": "Successfully logged in",
    "loginDescription": "Please log in to get started",
    "titleRegisterUser": "📋 Registered Users",
    "titleUsers": "Users",
    "titleClients": "Clients",
    "titleCalendar": "Calendar",
    "titleInterview": "Interview",
    "titlePreliminarData": "Preliminary Data",
    "connectToGoogle": "Connect to Google Calendar",
    "calendarNoEvents": "No upcoming events.",
    "calendarLinkButton": "Add or edit meeting",
    "homePageTitle": "Attract, Hire, and Develop Talent",
    "homePageSubtitle": "Our AI-powered platform, based on advanced behavioral science, enables candidate success and performance in any role.",
    "homeBenefits": "Benefits",
    "homeClientsTitle": "What do our clients say?",
    "homeTestimonial": [
        {"name": "Ana García", "testimonial": "This platform changed the way we hire. The results have been amazing."},
        {"name": "Carlos Méndez", "testimonial": "The system helped us identify high-potential candidates we wouldn’t have considered otherwise."},
        {"name": "Laura Pérez", "testimonial": "Thanks to the platform, we now have more engaged and productive employees."},
    ],
    "menuClientPlanning": "Planning",
    "InterviewDropdownText": "Person to evaluate",
    "InterviewFormacionAcademicaText": "Academic Background",
    "InterviewLanguages": "Languages",
    "InterviewIdiomas": ["Spanish", "English", "Portuguese"],
    "InterviewExperienciaProfesional": "Professional Experience",
    "InterviewSaveButton": "Save Report",
    "InterviewCreateFile": "Generate Report",
    "InverviewCompetenceTitle": "Competency Assessment",
    "Valor": "Rating",
    "SelectValue": "Select a value",
    "dataSavedCorrectlyMessage": "Data saved successfully",
    "dataSavedErrorMessage": "Error saving data",
}
