texts = {
    "greetings":"Hola",
    "title": "Bienvenido a P+Data",
    "username": "Email",
    "password": "Contraseña",
    "forgotPassword": "Olvidé mi contraseña",
    "loginButton": "Iniciar Sesión",
    "logoutButton": "Desloguearse",
    "errorRedirection": "Sesión expirada. Redirigiendo a login...",
    "IncorrectPassword": "Email o contraseña incorrectos. Intente nuevamente",
    "homeLoginRedirect":"Redirigiendo a la página de login...",
    "logoutMessage": "Deslogueo exitoso",
    "loginMessage": "Sesión iniciada exitosamente",
    "loginDescription": "Por favor, para comenzar inicie sesión",
    "titleRegisterUser":"📋 Usuarios registrados",
    "titleUsers":"Usuarios",
    "titleClients":"Clientes",
    "titleCalendar":"Agenda",
    "titleInterview":"Entrevista",
    "titlePreliminarData":"Datos Preliminares",
    "connectToGoogle":"Conectar con Google Calendar",
    "calendarNoEvents":"No hay eventos próximos.",
    "calendarLinkButton":"Agregar o modificar reunión",
    "homePageTitle":"Atraiga, Contrate y desarrolle a los talentos",
    "homePageSubtitle":"Nuestra plataforma impulsada por inteligencia artificial y configurada según la ciencia avanzada del comportamiento le permite el éxito y el rendimiento de los candidatos de cualquier puesto.",
    "homeBenefits":"Beneficios",
    "homeClientsTitle":"¿Qué dicen nuestros clientes?",
    "homeTestimonial" : [
    {"name": "Ana García", "testimonial": "Esta plataforma cambió la manera en que contratamos. Los resultados han sido sorprendentes."},
    {"name": "Carlos Méndez", "testimonial": "El sistema nos ayudó a identificar candidatos con un alto potencial que no habríamos considerado de otra manera."},
    {"name": "Laura Pérez", "testimonial": "Gracias a la plataforma, ahora tenemos empleados más comprometidos y productivos."},
],
    "menuClientPlanning":"Planning",
    "InterviewDropdownText":"Persona a evaluar",
    "InterviewFormacionAcademicaText":"Formación Académica",
    "InterviewLanguages":"Idiomas",
    "InterviewIdiomas" : ["Español", "Inglés", "Portugués"],
    "InterviewSelectLang" : "Seleccioná un idioma:",
    "InterviewSelectLangNivel" : "Seleccioná tu nivel:",
    "InterviewSelectAddLang" : "Agregar Idioma",
    "InterviewSelectAddedLang":"Idiomas agregados:",
    "InterviewLangAlreadyAdded":"Este idioma ya fue agregado.",
    "InterviewExperienciaProfesional":"Experiencia Profesional",
    "InterviewSaveButton":"Guardar informe",
    "InterviewCreateFile":"Generar informe",
    "InverviewCompetenceTitle":"Valoración de Competencias",
    "InverviewCompetenceAdd":"Ingresa una competencia",
    "InterviewCapacidadPotencialActual": "Capacidad Potencial Actual",
    "InterviewCapacidadPotencialFutura": "Capacidad Potencial Futura",
    "InterviewConclusiones": "Conclusiones",
    "InterviewRecomendaciones": "Recomendaciones",
    "InterviewAccionesDesarrollo": "Propuesta acciones de desarrollo",
    "Valor":"Valor",
    "Comment":"Comentario",
    "SelectValue":"Selecciona un valor",
    "dataSavedCorrectlyMessage":"Data guardada correctamente",
    "dataSavedErrorMessage":"Error al guardar",
    "dataNoReportFound":"No se encontró informe, guarde antes de generar el informe"

}
