texts = {
  "greetings": "Olá",
  "title": "Bem-vindo à P+Data",
  "username": "Email",
  "password": "Senha",
  "forgotPassword": "Esqueci minha senha",
  "loginButton": "Entrar",
  "logoutButton": "Sair",
  "errorRedirection": "Sessão expirada. Redirecionando para login...",
  "IncorrectPassword": "Email ou senha incorretos. Tente novamente",
  "homeLoginRedirect": "Redirecionando para a página de login...",
  "logoutMessage": "Logout realizado com sucesso",
  "loginMessage": "Sessão iniciada com sucesso",
  "loginDescription": "Por favor, entre para começar",
  "titleRegisterUser": "📋 Usuários Registrados",
  "titleUsers": "Usuários",
  "titleClients": "Clientes",
  "titleCalendar": "Agenda",
  "titleInterview": "Entrevista",
  "titlePreliminarData": "Dados Preliminares",
  "connectToGoogle": "Conectar com o Google Calendar",
  "calendarNoEvents": "Sem eventos próximos.",
  "calendarLinkButton": "Adicionar ou editar reunião",
  "homePageTitle": "Atraia, Contrate e Desenvolva Talentos",
  "homePageSubtitle": "Nossa plataforma, impulsionada por IA e baseada na ciência comportamental avançada, promove o sucesso e desempenho dos candidatos em qualquer cargo.",
  "homeBenefits": "Benefícios",
  "homeClientsTitle": "O que dizem nossos clientes?",
  "homeTestimonial": [
    {"name": "Ana García", "testimonial": "Essa plataforma mudou a forma como contratamos. Os resultados foram surpreendentes."},
    {"name": "Carlos Méndez", "testimonial": "O sistema nos ajudou a identificar candidatos com alto potencial que não consideraríamos de outra forma."},
    {"name": "Laura Pérez", "testimonial": "Graças à plataforma, agora temos colaboradores mais engajados e produtivos."}
  ],
  "menuClientPlanning": "Planejamento",
  "InterviewDropdownText": "Pessoa a ser avaliada",
  "InverviewTitlePerfilProfesional": "PERFIL PROFISSIONAL",
  "InterviewValoracionCompentencias": "AVALIAÇÃO DE COMPETÊNCIAS",
  "InterviewEvaluacionPotencial": "AVALIAÇÃO DE POTENCIAL",
  "InterviewBalanceEmocional": "EQUILÍBRIO EMOCIONAL",
  "InterviewMotivacionIntereses": "MOTIVAÇÕES E INTERESSES",
  "InterviewMotivacionesSubtitle": "Aspiração de Crescimento",
  "InterviewDisponibildadGeografica": "Disponibilidade geográfica",
  "InterviewDisponibilidadList": ["Parcial", "Total", "Nenhuma"],
  "InterviewBreveDescripcion": "Descrição breve",
  "InterviewConclusiones": "CONCLUSÕES",
  "InterviewFormacionAcademicaText": "Formação Acadêmica",
  "InterviewLanguages": "Idiomas",
  "InterviewIdiomas": ["Espanhol", "Inglês", "Português"],
  "InterviewSelectLang": "Selecione um idioma:",
  "InterviewSelectLangNivel": "Selecione seu nível:",
  "InterviewSelectAddLang": "Adicionar Idioma",
  "InterviewSelectAddedLang": "Idiomas adicionados:",
  "InterviewLangAlreadyAdded": "Este idioma já foi adicionado.",
  "InterviewExperienciaProfesional": "Experiência Profissional",
  "InterviewSaveButton": "Salvar relatório",
  "InterviewCreateFile": "Gerar relatório",
  "InverviewCompetenceTitle": "Avaliação de Competências",
  "InverviewCompetenceAdd": "Digite uma competência",
  "AddButton": "Adicionar",
  "DeleteButton": "Excluir",
  "NoDataYet": "Ainda não há dados",
  "InverviewCompetenceAdded": "Competências adicionadas:",
  "InverviewMotivacionAdded": "Aspirações adicionadas:",
  "InterviewFortalezayAreasDesarrollo": "Pontos fortes e áreas de desenvolvimento",
  "InverviewFortalezaAdded": "Pontos fortes adicionados:",
  "InterviewFortalezaTitle": "Pontos Fortes",
  "InterviewAreaTitle": "Áreas de Desenvolvimento",
  "InverviewAreasAdded": "Áreas adicionadas:",
  "InverviewPotencial": "Potencial:",
  "InterviewPotencialNivel": ["Alto", "Médio", "Baixo"],
  "InterviewCapacidadPotencialActual": "Capacidade Potencial Atual",
  "InterviewCapacidadPotencialFutura": "Capacidade Potencial Futura",
  "InterviewGraficoProgreso": "Gráfico de Progresso do Potencial",
  "InterviewCPA": ["IB", "IM", "IA", "IIB", "IIM", "IIA", "IIIB", "IIIM", "IIIA", "IVB", "IVM", "IVA", "VB", "VM", "VA"],
  "InterviewCPA5Title": "CPA EM 5 ANOS",
  "InterviewCPA10Title": "CPA EM 10 ANOS",
  "InterviewModo": ["I", "II", "III", "IV", "V", "VI", "VII"],
  "InterviewModoTitle": "MODO",
  "InterviewConclusionesTitle": "CONCLUSÕES",
  "InterviewConclusiones": "Conclusões",
  "InterviewRecomendaciones": "Recomendações",
  "InterviewAccionesDesarrollo": "Proposta de ações de desenvolvimento",
  "Valor": "Valor",
  "Comment": "Comentário:",
  "SelectValue": "Selecione um valor",
  "dataSavedCorrectlyMessage": "Dados salvos com sucesso",
  "dataSavedErrorMessage": "Erro ao salvar dados",
  "dataNoReportFound": "Nenhum relatório encontrado, salve antes de gerar o relatório"
}
