texts = {
    "greetings": "Olá",
    "title": "Bem-vindo ao P+Data",
    "username": "Email",
    "password": "Senha",
    "forgotPassword": "Esqueci minha senha",
    "loginButton": "Entrar",
    "logoutButton": "Sair",
    "errorRedirection": "Sessão expirada. Redirecionando para o login...",
    "IncorrectPassword": "Email ou senha incorretos. Tente novamente",
    "homeLoginRedirect": "Redirecionando para a página de login...",
    "logoutMessage": "Logout realizado com sucesso",
    "loginMessage": "Login realizado com sucesso",
    "loginDescription": "Por favor, faça login para começar",
    "titleRegisterUser": "📋 Usuários registrados",
    "titleUsers": "Usuários",
    "titleClients": "Clientes",
    "titleCalendar": "Agenda",
    "titleInterview": "Entrevista",
    "titlePreliminarData": "Dados Preliminares",
    "connectToGoogle": "Conectar com o Google Calendar",
    "calendarNoEvents": "Sem eventos próximos.",
    "calendarLinkButton": "Adicionar ou modificar reunião",
    "homePageTitle": "Atrair, Contratar e Desenvolver Talentos",
    "homePageSubtitle": "Nossa plataforma com inteligência artificial e baseada em ciência comportamental avançada permite o sucesso e desempenho dos candidatos para qualquer cargo.",
    "homeBenefits": "Benefícios",
    "homeClientsTitle": "O que dizem nossos clientes?",
    "homeTestimonial": [
        {"name": "Ana García", "testimonial": "Esta plataforma mudou a forma como contratamos. Os resultados foram surpreendentes."},
        {"name": "Carlos Méndez", "testimonial": "O sistema nos ajudou a identificar candidatos com alto potencial que não consideraríamos de outra forma."},
        {"name": "Laura Pérez", "testimonial": "Graças à plataforma, agora temos funcionários mais engajados e produtivos."}
    ],
    "menuClientPlanning": "Planejamento",
    "InterviewDropdownText": "Pessoa a ser avaliada",
    "InterviewFormacionAcademicaText": "Formação Acadêmica",
    "InterviewLanguages": "Idiomas",
    "InterviewIdiomas": ["Espanhol", "Inglês", "Português"],
    "InterviewSelectLang": "Selecione um idioma:",
    "InterviewSelectLangNivel": "Selecione seu nível:",
    "InterviewSelectAddLang": "Adicionar idioma",
    "InterviewSelectAddedLang": "Idiomas adicionados:",
    "InterviewLangAlreadyAdded": "Este idioma já foi adicionado.",
    "InterviewExperienciaProfesional": "Experiência Profissional",
    "InterviewSaveButton": "Salvar relatório",
    "InterviewCreateFile": "Gerar relatório",
    "InverviewCompetenceTitle": "Avaliação de Competências",
    "InverviewCompetenceAdd": "Digite uma competência",
    "InterviewCapacidadPotencialActual": "Capacidade Potencial Atual",
    "InterviewCapacidadPotencialFutura": "Capacidade Potencial Futura",
    "InterviewConclusiones": "Conclusões",
    "InterviewRecomendaciones": "Recomendações",
    "InterviewAccionesDesarrollo": "Proposta de ações de desenvolvimento",
    "Valor": "Valor",
    "Comment": "Comentário",
    "SelectValue": "Selecione um valor",
    "dataSavedCorrectlyMessage": "Dados salvos com sucesso",
    "dataSavedErrorMessage": "Erro ao salvar",
    "dataNoReportFound": "Nenhum relatório encontrado, salve antes de gerar o relatório"
}
